name: pick_location_api
description: Pick Location API with JWT authentication
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.7
  dart_frog: ^1.2.6
  dart_jsonwebtoken: ^3.3.1
  dart_odbc: ^6.2.0
  dotenv: ^4.2.0
  equatable: ^2.0.8
  redis: ^4.0.0
  # mssql_connection: ^2.0.2



dev_dependencies:
  build_runner: ^2.10.5
  dart_frog_gen: ^2.0.2
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.0.0
