name: pick_location_api
description: Pick Location API with JWT authentication
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_jsonwebtoken: ^2.12.0
  dart_odbc: ^1.0.2
  dotenv: ^4.2.0
  equatable: ^2.0.3
  redis: ^4.0.0
  # mssql_connection: ^2.0.2



dev_dependencies:
  build_runner: ^2.4.0
  dart_frog_gen: ^2.0.0
  mocktail: ^1.0.3
  test: ^1.24.0
  very_good_analysis: ^5.1.0
